// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortUrlMvc.Models;

namespace ShortUrlMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190614040243_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShortUrlMvc.Models.LongUrl", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Url");

                    b.HasKey("ID");

                    b.ToTable("LongUrls");
                });

            modelBuilder.Entity("ShortUrlMvc.Models.ShortUrl", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LongUrlID");

                    b.Property<string>("Postfix");

                    b.Property<string>("Prefix");

                    b.HasKey("ID");

                    b.HasIndex("LongUrlID");

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("ShortUrlMvc.Models.ShortUrl", b =>
                {
                    b.HasOne("ShortUrlMvc.Models.LongUrl", "LongUrl")
                        .WithMany()
                        .HasForeignKey("LongUrlID");
                });
#pragma warning restore 612, 618
        }
    }
}
